module.exports = {
  SPEED_LIMIT: 'Много запросов',
  FORBIDDEN: 'Запрещено',
  DOUBLE: 'Такой e-mail уже загистрирован',
  WRONG_WAY: 'Не верный путь',
  INVALID_ID: 'Не верный ID',
  VALIDATION_ERROR: 'Ошибка валидации',
  NOT_FILLING: 'Не заполнены обязательные значения',
  REGISTRATION_ERROR: 'Ошибка регистрации',
  AUTHORIZATION_REQUIRED: 'Необходима авторизация',
  AUTHENTICATION_ERROR: 'Ошибка аутентификации',
  AUTHORIZATION_ERROR: 'Ошибка авторизации',
  ERROR_EMAIL_PASS: 'Неправильные почта или пароль',
  INVALID_EMAIL: 'Не корректный e-mail',
};
